server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${ENV_DB_HOST}:5432/${ENV_DB_NAME}
    username: ${ENV_DB_USER}
    password: ${ENV_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ENV_MAIL_USER}
    password: ${ENV_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  send:
    period: '0 */1 * * * *'
    from: ${ENV_MAIL_USER}

form:
  google-application-name: zdrovi-dev
  google-credentials-file: zdrovi-368272ced627.json
  google-form-id: ${ENV_GOOGLE_FORM_ID}