server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://xevix.tplinkdns.com:5432/zdrovi
    username: postgres
    password: 5f2Sm![2?CSb#quG
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: info.zdrovi@gmail.com
    password: 'aajd bbkv ckjh fonb'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


email:
  send:
    period: '0 */1 * * * *'
    from: info.zdrovi@gmail.com

algorithm:
  label_matching_min: 1.0
  course_length: 5
  period: '0 0 * * * *'
