version: 0.2

env:
    variables:
        PROJECT_NAME: scheduler

phases: 
    install:
        runtime-versions:
            java: corretto21
        commands:
            - apt update -y
            - apt install docker.io curl -y
            - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
            - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    pre_build:
        commands:
            - cd scheduler
            - echo "Fetching repository token ..."
            - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain zdrovi --domain-owner 396913738285 --region eu-central-1 --query authorizationToken --output text`
            - echo "Pulling settings.xml"
            - aws s3 cp s3://zdrovi-infra/zdrovi_settings.xml zdrovi_settings.xml
    build:
        commands:
            - echo "Building ..."
            - mvn -s zdrovi_settings.xml clean package -DskipTests
    post_build:
        commands:
            - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 396913738285.dkr.ecr.eu-central-1.amazonaws.com
            - docker build -t zdrovi .
            - docker tag zdrovi:scheduler 396913738285.dkr.ecr.eu-central-1.amazonaws.com/zdrovi:scheduler
            - docker push 396913738285.dkr.ecr.eu-central-1.amazonaws.com/zdrovi:scheduler

cache:
    paths:
        - '/root/.m2/**/*'
        - '/root/.npm/**/*'
        - '/root/.pip-cache/**/*'
        - '/root/.docker/**'