version: 0.2

env:
    variables:
        PROJECT_NAME: parent

phases: 
    install:
        runtime-versions:
            java: corretto21
    pre_build:
        commands:
            - cd parent
            - echo "Fetching repository token ..."
            - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain zdrovi --domain-owner 396913738285 --region eu-central-1 --query authorizationToken --output text`
            - echo "Pulling settings.xml"
            - aws s3 cp s3://zdrovi-infra/zdrovi_settings.xml zdrovi_settings.xml
    build:
        commands:
            - echo "Building ..."
            - mvn -s zdrovi_settings.xml clean package
    post_build:
        commands:
            - echo "Publishing to artifact repository ..."
            - mvn -s zdrovi_settings.xml deploy
cache:
    paths:
        - '/root/.m2/**/*'
        - '/root/.npm/**/*'
        - '/root/.pip-cache/**/*'
        - '/root/.docker/**'