openapi: 3.0.3

info:
  title: Zdrovi
  description: |-
    This is Zdrovi API
  contact:
    email: wggajda@gmail.com
  version: 0.0.1

servers:
  - url: https://todo

tags:
  - name: user
  - name: label

paths:

  /user:
    post:
      tags:
        - user
      operationId: postUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

    delete:
      tags:
        - user
      operationId: deleteUser
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: john
          required: true
        - in: query
          name: email
          schema:
            type: string
            example: john@email.com
          required: true
      responses:
        '200':
          description: Successful operation
        '400':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

  /label:

    post:
      tags:
        - label
      operationId: postLabel
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Label"
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

    get:
      tags:
        - label
      operationId: getLabel
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Label"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: John
        email:
          type: string
          example: john@email.com
        labels_matchings:
          type: array
          items:
            $ref: "#/components/schemas/LabelMatching"

    Label:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    LabelMatching:
      type: object
      properties:
        tag_id:
          type: integer
          format: int64
        matching:
          type: integer
          format: int8